---
# Show all available Openstack images
- name: Get available openstack images
  os_image_info:
  register: image_result

- name: Get image list
  set_fact:
    image_facts: "{{ image_facts|default([]) + [ {'name': item.name, 'id': item.id} ] }}"
  loop: '{{ image_result.openstack_image }}'
  when: item.name is defined

- name: Show images
  debug:
    msg: "Image name: {{ item.name }}; Image id: {{ item.id }}"
  loop: '{{ image_facts }}'