ansible_user: ubuntu
remote_working_directory: /home/ubuntu/COMP90024
git_rep: /home/ubuntu/COMP90024/COMP90024-Assignment2

ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ansible_ssh_private_key_file: "config/mrcSSH.pem"


proxy_env:
  HTTP_PROXY= http://wwwproxy.unimelb.edu.au:8000/
  http_proxy= http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY= http://wwwproxy.unimelb.edu.au:8000/
  https_proxy= http://wwwproxy.unimelb.edu.au:8000/

  no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au