# Qi Li & 1138875 & lql4@student.unimelb.edu.au
# Yuheng Guo & 1113036 & yuhengg1@student.unimelb.edu.au
# Zhaoyang Zhang  & 1240942 & zhaoyangz1@student.unimelb.edu.au
# Zhaoyu Wei  & 1258372 & zhangyuw@student.unimelb.edu.au
# Xiaohan Ma  & 1145763 & mxm3@student.unimelb.edu.au
# Common vars
availability_zone: melbourne-qh2-uom
instance_image: aaddbad8-87d7-4ed7-9382-409b9bc42ca6
instance_key_name: mrcSSH

# Security group for instance1-instance4
security_groups:
  - name: instance1_security_group
    description: "instance1 security group"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

  - name: instance2_security_group
    description: "instance2 security group"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

  - name: instance3_security_group
    description: "instance3 security group"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

  - name: instance4_security_group
    description: "instance4 security group"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0


# Volume, arrange size and position
volumes:
  - vol_name: instance1_volume
    vol_size: 140
    device: /dev/vdb
    mountpoint: /data

  - vol_name: instance2_volume
    vol_size: 140
    device: /dev/vdb
    mountpoint: /data

  - vol_name: instance3_volume
    vol_size: 140
    device: /dev/vdb
    mountpoint: /data

  - vol_name: instance4_volume
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data

# Instance, set default ids as [], and add instance1_volumes to it
instances:
  - name: instance1
    security_groups: instance1_security_group
    volumes: ['instance1_volume']
    volumes_ids: "{ instance1_volumes|default([]) }"
    instance_flavor: uom.mse.2c9g

  - name: instance2
    security_groups: instance2_security_group
    volumes: [ 'instance2_volume' ]
    volumes_ids: "{ instance2_volumes|default([]) }"
    instance_flavor: uom.mse.2c9g

  - name: instance3
    security_groups: instance3_security_group
    volumes: [ 'instance3_volume' ]
    volumes_ids: "{ instance3_volumes|default([]) }"
    instance_flavor: uom.mse.2c9g

  - name: instance4
    security_groups: instance4_security_group
    volumes: [ 'instance4_volume' ]
    volumes_ids: "{ instance4_volumes|default([]) }"
    instance_flavor: uom.mse.2c9g



