---
# Qi Li & 1138875 & lql4@student.unimelb.edu.au
# Yuheng Guo & 1113036 & yuhengg1@student.unimelb.edu.au
# Zhaoyang Zhang  & 1240942 & zhaoyangz1@student.unimelb.edu.au
# Zhaoyu Wei  & 1258372 & zhangyuw@student.unimelb.edu.au
# Xiaohan Ma  & 1145763 & mxm3@student.unimelb.edu.au
# Create volumes from vars
- name: Create volume(s) on NeCTAR
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."