---
# Dependencies on the host
# sudo apt-get install python3-pip
- name: Install pip
  become: yes
  apt:
    name: ['python3-dev', 'python3-setuptools','python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip', 'openstacksdk']
    state: latest