---
# Qi Li & 1138875 & lql4@student.unimelb.edu.au
# Yuheng Guo & 1113036 & yuhengg1@student.unimelb.edu.au
# Zhaoyang Zhang  & 1240942 & zhaoyangz1@student.unimelb.edu.au
# Zhaoyu Wei  & 1258372 & zhangyuw@student.unimelb.edu.au
# Xiaohan Ma  & 1145763 & mxm3@student.unimelb.edu.au
# Dependencies on the host
# sudo apt-get install python3-pip
- name: Install pip
  become: yes
  apt:
    name: ['python3-dev', 'python3-setuptools','python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip', 'openstacksdk']
    state: latest