---
# Qi Li & 1138875 & lql4@student.unimelb.edu.au
# Yuheng Guo & 1113036 & yuhengg1@student.unimelb.edu.au
# Zhaoyang Zhang  & 1240942 & zhaoyangz1@student.unimelb.edu.au
# Zhaoyu Wei  & 1258372 & zhangyuw@student.unimelb.edu.au
# Xiaohan Ma  & 1145763 & mxm3@student.unimelb.edu.au
- name: install dependencies
  become: yes
  apt:
    name:
      ["unzip"]
    state: latest
    install_recommends: no
    update_cache: yes

# create dir
- name: Creates directory
  file:
    path: /home/ubuntu/COMP90024/CouchDB/dataUpload
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
    recurse: yes

# Unrar file
- name: extract archive
  become: yes
  unarchive:
    src: "/home/ubuntu/COMP90024/CouchDB/dataUpload.zip"
    dest: "/home/ubuntu/COMP90024/CouchDB/"
    remote_src: true
    validate_certs: true


- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: "~/.docker"
    state: "directory"

- name: Ensure Docker client proxy settings are present on the server
  become: yes
  copy:
    content: "{{ docker_proxy_settings }}"
    dest: ~/.docker/config.json

# Stop existing Docker containers
- name: Stop crawler Docker container _location
  become: yes
  docker_container:
    name: couchdb_data_upload
    state: absent

- name: Build an image and push it to local repo
  docker_image:
    build:
      path: "/home/ubuntu/COMP90024/CouchDB"
      pull: yes
    name: couchdb_data_upload
    tag: latest
    source: build
    force: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: Create and start crawler Docker container
  become: yes
  docker_container:
    name: couchdb_data_upload
    image: couchdb_data_upload
    state: started
    pull: false
    recreate: true
    restart_policy: always