- hosts: instances
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/constant.yaml
    - host_vars/deploy.yaml
  gather_facts: true

  roles:
    - role: install-add-proxy
    - role: install-dependencies
    - role: install-mount-volume