- hosts: instances

  vars_files:
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - role: install-add-proxy
    - role: install-dependencies
    - role: install-clone-github-rep
    - role: install-mount-volume